### ISSUE TITLE
Invalid response status after update to 0.4.0

### ISSUE THREAD

**Issue by gabscogna** [IanVS/vitest-fetch-mock#25]
I ran in problem with the newer version.
I have a test like this:

```javascript
// ...
fetchMocker.mockResponseOnce('', { status: 204 });
// ...
```

But when I run the tests, it give me the error:

```text
TypeError: Response constructor: Invalid response status code 204
 ❯ buildResponse node_modules/vitest-fetch-mock/src/index.ts:388:12
 ❯ node_modules/vitest-fetch-mock/src/index.ts:59:1
```
----

It should accept send `null` as response body here:
https://github.com/IanVS/vitest-fetch-mock/blob/6b4ba2e4155143eb55432007eb6f05bf0dbf1cc0/src/index.ts#L307

`type ResponseBody = string | null;`

...and here:
https://github.com/IanVS/vitest-fetch-mock/blob/6b4ba2e4155143eb55432007eb6f05bf0dbf1cc0/src/index.ts#L381

`if (responseProviderOrBody === null || typeof responseProviderOrBody === 'string') {`

So this will work:

```javascript
// ...
fetchMocker.mockResponseOnce(null, { status: 204 });
// ...
```

**Comment by dirkluijk** [comment]
Took me a moment to figure out what's happening here, but I found out.

Before, we were relying on `cross-fetch`:
```ts
import { Response } from 'cross-fetch';

new Response('', { status: 204 })
```
which works fine.

However, when running `new Response('', { status: 204 })` in a Node.js or browser environment without polyfills, it throws an error:
- `Failed to construct 'Response': Response with null body status cannot have body` in Chrome
- `TypeError: Response constructor: Invalid response status code 204` in Node.js
- `TypeError: Response with null body status cannot have body` in Deno

This is [by design](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204). There are two solutions:

1) rewrite your code to:
```ts
// either:
fetchMocker.mockResponseOnce(() => ({ status: 204 }));
// or:
fetchMocker.mockResponseOnce(() => new Response(null, { status: 204 }));
```

2) we adjust `vitest-fetch-mock` to accept `null` as response body, which makes sense to me, but note that this wasn't possible in previous version either. We just broke it by replacing the incorrect polyfill with the correct implementation.

@IanVS let me know what you think. I'm willing to make a fix if we agree on solution 2.

**Comment by dirkluijk** [comment]
Apart from making the response body nullable in `mockResponse(string: ResponseBody, params?: MockParams)`, I opened [another MR](https://github.com/IanVS/vitest-fetch-mock/pull/26) which enables you to also write:
```ts
fetchMocker.mockResponseOnce({ status: 204 });
fetchMocker.mockResponseOnce(new Response(null, { status: 204 }));
```

**Comment by gabscogna** [comment]
Thank you @dirkluijk I updated here and everything works fine now with 0.4.1 :)
